[DS21]
type_db = mysql
database = 007
server = localhost
port = 0
username = admin
password = exactwinkel

[EXACT]
type_db = mssql
database = 007
server = 192.168.0.25
port = 1433
username = ruben
password = exactwinkel

[TABLES]
Items = SELECT ID, case when picture is null then 'N' else 'Y' end picture, ItemCode, Description, SecurityLevel, [Type], Assortment, Class_01, Class_02, Class_03, Class_04, Class_05, Class_06, Class_07, Class_08, Class_09, Class_10, IsSalesItem, IsPurchaseItem, IsServiceItem, IsTextItem, IsStockItem, IsSerialNumberItem, IsSubAssemblyItem, IsPriceRegulationItem, IsBackOrderItem, IsFractionAllowedItem, IsPrintItem, EANCode, BARCode, BARCodeType, StockCurrency, StockValuationType, StockValuationDate, WareHouse, WareHouseLocation, CostPriceCurrency, CostPriceCalculated, CostPriceCalculatedManually, CostPriceStandard, PurchaseCurrency, PurchasePrice, PurchaseVATPerc, PurchaseVATIncl, SalesPriceType, DimensionsInText, WeightInText, PictureFilename, UserField_01, UserField_02, UserField_03, UserField_04, UserField_05, UserField_06, UserField_07, UserField_08, UserField_09, UserField_10, UserDate_01, UserDate_02, UserDate_03, UserDate_04, UserDate_05, UserNumber_01, UserNumber_02, UserNumber_03, UserNumber_04, UserNumber_05, UserYesNo_01, UserYesNo_02, UserYesNo_03, UserYesNo_04, UserYesNo_05, RegulationType, RegulationFixedAmount, RegulationAmount, RegulationCurrency, RegulationPercentage, RegulationItemsIncluded, RegulationItemsExcluded, RegulationPriority, ItemCodeReplacement, ItemType, IsAssembled, SearchCode, eenh_verk, aant_verp, SalesPackagePrice, PurchaseOrderAdviceCode, SalesVatCode, PurchaseVatCode, StatisticalNumber, PackageDescription, SerialBatchItem, IsBatchItem, IsBackToBackOrder, UserNumber_06, UserNumber_07, UserNumber_08, PurchaseFactor, SalesFactor, StatisticalUnits, NetWeight, GrossWeight, ExtraDutyVATcode, SalesMarginPercent, status, [Condition], IsDiscount, IsExplode, IsCentralItem, lev_crdnr, Percentage_1, Percentage_2, Description_0, Description_1, Description_2, Description_3, Description_4, LongDescription, GLAccountRevenue, GLAccountCost, GLAccountDistribution, GLAccountAsset, syscreated, syscreator, sysmodified, sysmodifier, sysguid, TextDescription, LevelCode, CountingCycle, RequiresApprovedSupplier FROM Items
artext = SELECT ID, ex_artcode, artcode, tekst, breedte_i, syscreated, syscreator, sysmodified, sysmodifier, sysguid FROM artext
staffl = SELECT ID, prijslijst, artcode, kort_pbn, prijs83, aantal1, bedr1, aantal2, bedr2, aantal3, bedr3, aantal4, bedr4, aantal5, bedrag5, quantity6, price6, quantity7, price7, quantity8, price8, quantity9, price9, quantity10, price10, AccountID, unitcode, unitfactor, validfrom, validto, syscreated, syscreator, sysmodified, sysmodifier, sysguid FROM staffl
ItemAssortment = SELECT ID, Assortment, Code, Description, SecurityLevel, OwnerPerson, UseReleases, UseTranslations, UseCountries, UseCatalog, CatalogItemSelection, CatalogOrder, CatalogClass_1, CatalogClass_2, CatalogClass_3, UseContract, ContractItemSelection, ContractDocGroup, ContractDocCategory, ContractDocSubCategory, ContractDocSecurity, ContractComponentProgID, ContractComponentParameter, ContractReleaseMandatory, Note, Picture, PictureFilename, AllowInCatalog, AllowNewItem, AllowNewContract, AllowNewDocument, LabelUserField_01, LabelUserField_02, LabelUserField_03, LabelUserField_04, LabelUserField_05, LabelUserField_06, LabelUserField_07, LabelUserField_08, LabelUserField_09, LabelUserField_10, LabelUserDate_01, LabelUserDate_02, LabelUserDate_03, LabelUserDate_04, LabelUserDate_05, LabelUserNumber_01, LabelUserNumber_02, LabelUserNumber_03, LabelUserNumber_04, LabelUserNumber_05, LabelUserYesNo_01, LabelUserYesNo_02, LabelUserYesNo_03, LabelUserYesNo_04, LabelUserYesNo_05, LabelNUserField_01, LabelNUserField_02, LabelNUserField_03, LabelNUserField_04, LabelNUserField_05, LabelNUserField_06, LabelNUserField_07, LabelNUserField_08, LabelNUserField_09, LabelNUserField_10, LabelNUserDate_01, LabelNUserDate_02, LabelNUserDate_03, LabelNUserDate_04, LabelNUserDate_05, LabelNUserNumber_01, LabelNUserNumber_02, LabelNUserNumber_03, LabelNUserNumber_04, LabelNUserNumber_05, LabelNUserYesNo_01, LabelNUserYesNo_02, LabelNUserYesNo_03, LabelNUserYesNo_04, LabelNUserYesNo_05, StatNumber, Costunit, GLRevenue, GLDeferredRevenue, GLDeferredCost, GLDiscount, GLCostOfGoodsSold, GLStock, GLPriceDifference, Description_0, Description_1, Description_2, Description_3, Description_4, syscreated, syscreator, sysmodified, sysmodifier, sysguid, PriceSecurityLevel FROM ItemAssortment

[FILES]
directory = /home/exact/Documents/winkel
products = SELECT * FROM products
wholesale = SELECT * FROM wholesale
extra_fields = SELECT * FROM extra_fields
categories = SELECT * FROM categories
multi_language = SELECT * FROM prod_taal WHERE fields IS NOT NULL ORDER BY fields
FR = SELECT * FROM prod_taal WHERE fields IS NOT NULL AND taal = 'FR' ORDER BY fields
DE = SELECT * FROM prod_taal WHERE fields IS NOT NULL AND taal = 'DE' ORDER BY fields
IT = SELECT * FROM prod_taal WHERE fields IS NOT NULL AND taal = 'IT' ORDER BY fields
EN = SELECT * FROM prod_taal WHERE fields IS NOT NULL AND taal = 'EN' ORDER BY fields
ES = SELECT * FROM prod_taal WHERE fields IS NOT NULL AND taal = 'ES' ORDER BY fields

[MAPPINGS]
cols = exact_id, exact_code_1, exact_code_2, exact_description, exact_created, exact_category_code, exact_category, xcart_id, xcart_code, xcart_created, xcart_category_code, xcart_category, reden
step03 = truncate table mapping
step06 = truncate table mapping_temp01
step10 = insert into mapping (cols) ( select distinct * from step10 )
step20 = insert into mapping (cols) ( select distinct * from step20 )
step30 = insert into mapping_temp01 ( select distinct * from step30 )
step40 = insert into mapping (cols) ( select distinct * from step40 )
step50 = insert into mapping (cols) ( select distinct * from step50 )
step60 = insert into mapping (cols) ( select distinct * from step60 )
step70 = truncate table taal_winkel_tbl
step80 = insert into taal_winkel_tbl ( select distinct * from taal_winkel )
step85 = truncate table tekst_match_tbl
step90 = insert into tekst_match_tbl ( select distinct * from tekst_match )

[EXCEL]
tekst_mismatch = select * from tekst_match_tbl
product_mismatch = select * from mapping
;where product_match != 'Gelijk' or tekst_match != 'Gelijk'

[PICTURES]
directory = /home/exact/Pictures/winkel
thumb_directory = /home/exact/Pictures/winkel/thumbnails
sql = select id, picture from Items where picture is not null
thumb_width = 80
thumb_height = 50
plaatjes = N
